export const ADD_ADDRESS = "ADD_ADDRESS";
export const REMOVE_ADDRESS = "REMOVE_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const SET_ADDRESS_LOADING = "SET_ADDRESS_LOADING";
export const SET_ADDRESS_ERROR = "SET_ADDRESS_ERROR";
